#pragma once
#define RR_SOUND "声音开"
#define RR_MUTED "静音"
#define RR_BOOST "连超加速"
#define RR_TEXT_TITLE "狂飙骑手"
#define RR_TEXT_SUBTITLE "落日海岸公路"
#define RR_TEXT_START "按 B 开始竞速"
#define RR_TEXT_LANES "A/C 换道"
#define RR_TEXT_ATTACK "B 攻击"
#define RR_TEXT_PAUSE_HINT "长按 B 暂停比赛"
#define RR_TEXT_POS "名次"
#define RR_TEXT_ARMOR "耐久"
#define RR_TEXT_BATTERY "电量"
#define RR_TEXT_HELP "躲避车辆 靠近骑手后攻击"
#define RR_TEXT_HIT "打"
#define RR_TEXT_KO "击退"
#define RR_TEXT_CRASH "撞车"
#define RR_TEXT_PAUSED "已暂停"
#define RR_TEXT_FINISH "冲线成功"
#define RR_TEXT_WRECKED "车辆损毁"
#define RR_TEXT_BREATH "歇一会 再上路"
#define RR_TEXT_RESUME "按 B 继续比赛"
#define RR_TEXT_HOME "长按 A 返回首页"
#define RR_TEXT_SCORE "得分"
#define RR_TEXT_KNOCKOUTS "击退骑手"
#define RR_TEXT_VICTORY "海岸公路属于你"
#define RR_TEXT_RETRY "再来一场吧"
#define RR_TEXT_REPLAY "按 B 再来一场"

#define RR_TEXT_STAGE1 "海岸练习"
#define RR_TEXT_STAGE2 "城市追逐"
#define RR_TEXT_STAGE3 "沙漠车流"
#define RR_TEXT_STAGE4 "雨夜山道"
#define RR_TEXT_STAGE5 "最终决战"
#define RR_TEXT_CHALLENGE1 "奖励 超车5次"
#define RR_TEXT_CHALLENGE2 "奖励 击退3人"
#define RR_TEXT_CHALLENGE3 "奖励 耐久50以上"
#define RR_TEXT_CHALLENGE4 "奖励 80秒内冲线"
#define RR_TEXT_CHALLENGE5 "奖励 前3名冲线"
#define RR_TEXT_NEXT "按 B 下一关"
#define RR_TEXT_ALL_CLEAR "全部通关"
#define RR_TEXT_STAGE_SELECT "A/C 选关 长 A 声音"
#define RR_TEXT_UNLOCKED "已解锁"
#define RR_TEXT_STAGE_LABEL "关卡"
#define RR_TEXT_BONUS "额外挑战"
#define RR_TEXT_COMPLETE "已完成"
#define RR_TEXT_NOT_COMPLETE "未完成"

#define RR_TEXT_COOLDOWN "B 冷却"
#define RR_TEXT_READY "B 就绪"

#define RR_TUTORIAL "A 左 C 右 躲车 B 攻击可选"
