#pragma once
#define SG_TITLE_TEXT "星港炮手"
#define SG_SUBTITLE "短 B 射击  长 B 蓄力"
#define SG_START "短按 B 开始"
#define SG_CONTROL "A/C 瞄准  B 松手射击"
#define SG_SELECT "A/C 选关  长 A 声音"
#define SG_PAUSED_TEXT "已暂停"
#define SG_FAILED_TEXT "星港失守"
#define SG_CLEAR_TEXT "星港守住了"
#define SG_WON "航道清空"
#define SG_RESUME "短按 B 继续"
#define SG_EXIT "长按 A 返回标题"
#define SG_HOME "长按 B 返回标题"
#define SG_RETRY "短按 B 重试"
#define SG_NEXT "短按 B 下一关"
#define SG_SCORE "分数"
#define SG_BEST "最佳"
#define SG_STAGE "关"
#define SG_PROGRESS "击落"
#define SG_SOUND "声音开"
#define SG_MUTED "声音关"
#define SG_CHARGING "松 B 发射穿透炮"
#define SG_NORMAL "松 B 发射普通弹"
#define SG_READY "穿透炮可用  长 C 暂停"
#define SG_COOLING "穿透冷却  普通弹可用"
#define SG_WARNING "敌弹预警"
#define SG_ARMOR "护甲"
#define SG_BOSS "旗舰"
static const char *const sg_stage_names[]={"静谧航道","巡航来袭","装甲突围","交错星轨","旗舰决战"};
