#pragma once
#define CB_MEDAL_GOAL "通关  无救援  连击三次"
#define CB_TITLE_TEXT "云间一跃"
#define CB_SUBTITLE "穿过云海 追逐落日"
#define CB_START "短按 B 开始"
#define CB_CONTROL "按住 B 蓄力 松手跳跃"
#define CB_PAUSE_HINT "长按 C 暂停"
#define CB_SELECT "A/C 选关 长 A 切换声音"
#define CB_MUTE "标题页长按 A 切换声音"
#define CB_STAGE "关卡"
#define CB_PROGRESS "落地"
#define CB_SCORE "得分"
#define CB_BEST "最佳"
#define CB_CHARGE "蓄力"
#define CB_READY "按住 B 准备跳跃"
#define CB_CAPPED "蓄力已满 松手起跳"
#define CB_PERFECT "精准连击"
#define CB_PAUSED_TEXT "已暂停"
#define CB_RESUME "短按 B 继续"
#define CB_EXIT "长按 A 返回标题"
#define CB_WON "挑战成功"
#define CB_FAILED_TEXT "再试一次"
#define CB_CLEAR_TEXT "全部通关"
#define CB_NEXT "短按 B 下一关"
#define CB_RETRY "短按 B 重试本关"
#define CB_HOME "长按 B 返回标题"
#define CB_MUTED "静音"
#define CB_SOUND "声音开"
static const char *const cb_stage_names[]={"晨雾初行","晴空漫步","晚霞窄桥","星夜高台","极光之旅"};

#define CB_RESCUE "短 A 救援一次  短 B 重来"
#define CB_FLYING "跃过云海"
#define CB_SCROLL "站稳脚步 准备下一跃"

#define CB_TUTORIAL "看轨迹 落点进入平台"
#define CB_RELEASE_HINT "落点合适 松 B 起跳"
