#pragma once
#define RP_MEDAL_GOAL "通关  无失误  收齐奖励"
#define RP_TITLE_TEXT "跃影疾行"
#define RP_SUBTITLE "越过屋顶  追逐晨光"
#define RP_START "短按 B 开始"
#define RP_CONTROL "A 前进  B 后退  C 跳跃"
#define RP_SELECT "A/C 选关  长 A 声音"
#define RP_LINK "松开移动键  再短按 C"
#define RP_PAUSED_TEXT "已暂停"
#define RP_FAILED_TEXT "回到检查点"
#define RP_CLEAR_TEXT "晨光抵达"
#define RP_WON "抵达终点"
#define RP_RESUME "短按 B 继续"
#define RP_EXIT "长按 A 返回标题"
#define RP_HOME "长按 B 返回标题"
#define RP_RETRY "短按 B 重玩"
#define RP_NEXT "短按 B 下一关"
#define RP_SCORE "分数"
#define RP_BEST "最佳"
#define RP_PROGRESS "路程"
#define RP_SOUND "声音开"
#define RP_MUTED "声音关"
#define RP_ACTION "A 前进  B 后退  C 跳跃"
#define RP_PAUSE "长按 C 暂停"
#define RP_JUMP_HINT "靠近亮边再跳"
#define RP_SAVED "检查点已记录"
#define RP_RESPAWN "已收集奖励保留"
static const char *const rp_stage_names[]={"清晨天台","错落街区","尖角试炼","流光机关","日出长廊"};
