#!/usr/bin/env python3
"""Generate/verify the 12px Chinese atlas used by the shared strip renderer."""
import argparse
import hashlib
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[3]
COPY = ROOT / 'main/games/brick_workshop/bw_copy.h'
FONT = ROOT / 'assets/fonts/brick_workshop_noto_sc_subset.otf'
OUT = ROOT / 'assets/fonts/brick_workshop_noto_sc_12.h'

def characters():
    return sorted(set(re.findall(r'[\u3400-\u9fff]', COPY.read_text())))

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--source', type=Path)
    args = parser.parse_args()
    chars = characters()
    source_hash = hashlib.sha256(COPY.read_bytes()).hexdigest()
    if args.check:
        content = OUT.read_text()
        present = {int(v, 16) for v in re.findall(r'\{0x([0-9A-F]{4}),', content)}
        assert present == {ord(c) for c in chars}, 'Chinese glyph coverage is stale'
        assert source_hash in content, 'UI copy changed: regenerate font'
        assert hashlib.sha256(FONT.read_bytes()).hexdigest() in content, 'Source font changed'
        print(f'Chinese glyph coverage: PASS ({len(chars)} characters at 12px)')
        sys.exit(0)
    sys.path.insert(0, str(ROOT / 'build/font-tools'))
    from PIL import Image, ImageDraw, ImageFont
    from fontTools import subset
    from fontTools.ttLib import TTFont
    if args.source:
        font = TTFont(args.source)
        missing = {ord(c) for c in chars} - set(font.getBestCmap())
        if missing: raise SystemExit(f'Missing source glyphs: {missing}')
        options = subset.Options()
        options.name_IDs = ['*']
        options.name_legacy = True
        options.name_languages = ['*']
        tool = subset.Subsetter(options=options)
        tool.populate(text=''.join(chars))
        tool.subset(font)
        font.save(FONT)
    font = ImageFont.truetype(str(FONT), 12)
    lines = ['/* Generated by tools/games/brick_workshop/generate_font.py. Noto Sans CJK SC, SIL OFL. */',
             f'/* copy sha256: {source_hash} */',
             f'/* font sha256: {hashlib.sha256(FONT.read_bytes()).hexdigest()} */',
             '#pragma once', '#include <stdint.h>',
             'typedef struct { uint16_t codepoint; uint16_t rows[14]; } bw_cjk_glyph_t;',
             'static const bw_cjk_glyph_t bw_cjk_glyphs[] = {']
    for char in chars:
        image = Image.new('L', (12, 14))
        ImageDraw.Draw(image).text((0, -2), char, font=font, fill=255)
        rows = [sum(1 << (11-x) for x in range(12) if image.getpixel((x,y)) >= 80) for y in range(14)]
        if not any(rows): raise SystemExit(f'Empty glyph: {char}')
        lines.append('    {0x%04X, {%s}},' % (ord(char), ','.join('0x%03X' % v for v in rows)))
    lines += ['};', '#define BW_CJK_GLYPH_COUNT (sizeof(bw_cjk_glyphs)/sizeof(bw_cjk_glyphs[0]))', '']
    OUT.write_text('\n'.join(lines))
    print(f'Generated {len(chars)} glyphs, {len(chars)*30} bytes of bitmap records')
