#!/usr/bin/env python3
"""Generate/verify native-size, antialiased Noto Sans text for Alley Ninja."""
import argparse
import hashlib
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[3]
COPY = ROOT / 'main/games/alley_ninja/an_copy.h'
FONT = ROOT / 'assets/fonts/alley_ninja_noto_sc_subset.otf'
OUT = ROOT / 'assets/fonts/alley_ninja_noto_sc_12.h'

def characters():
    return sorted(set(re.findall(r'[\u3400-\u9fff]', COPY.read_text())) | {chr(i) for i in range(32,127)})

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--source', type=Path)
    args = parser.parse_args()
    chars = characters()
    source_hash = hashlib.sha256(COPY.read_bytes()).hexdigest()
    if args.check:
        content = OUT.read_text()
        present = {int(v, 16) for v in re.findall(r'\{0x([0-9A-F]{4}),', content)}
        assert present == {ord(c) for c in chars}, 'Chinese glyph coverage is stale'
        assert source_hash in content, 'UI copy changed: regenerate font'
        assert hashlib.sha256(FONT.read_bytes()).hexdigest() in content, 'Source font changed'
        assert 'native sizes: 1,2,3; alpha: 4bpp' in content, 'Atlas format is stale'
        print(f'Font coverage: PASS ({len(chars)} glyphs, three native sizes, 4bpp)')
        sys.exit(0)
    sys.path.insert(0, str(ROOT / 'build/font-tools'))
    from PIL import Image, ImageDraw, ImageFont
    from fontTools import subset
    from fontTools.ttLib import TTFont
    if args.source:
        font = TTFont(args.source)
        missing = {ord(c) for c in chars} - set(font.getBestCmap())
        if missing: raise SystemExit(f'Missing source glyphs: {missing}')
        options = subset.Options()
        options.name_IDs = ['*']
        options.name_legacy = True
        options.name_languages = ['*']
        tool = subset.Subsetter(options=options)
        tool.populate(text=''.join(chars))
        tool.subset(font)
        font.save(FONT)
    lines = ['/* Generated by tools/games/alley_ninja/generate_font.py. Noto Sans CJK SC, SIL OFL. */',
             '/* native sizes: 1,2,3; alpha: 4bpp */',
             f'/* copy sha256: {source_hash} */',
             f'/* font sha256: {hashlib.sha256(FONT.read_bytes()).hexdigest()} */',
             '#pragma once', '#include <stdint.h>',
             'typedef struct { uint16_t codepoint; uint8_t scale,width,height,advance; uint32_t offset; } an_cjk_glyph_t;']
    records=[];bitmap=[]
    for scale in (1,2,3):
        for char in chars:
            ascii_char=ord(char)<128
            font=ImageFont.truetype(str(FONT),(10 if ascii_char else 12)*scale)
            width=max(1,int(font.getlength(char)+0.999)) if ascii_char else 12*scale
            height=14*scale
            image=Image.new('L',(width,height))
            ImageDraw.Draw(image).text((0,-(1 if ascii_char else 2)*scale),char,font=font,fill=255)
            pixels=[(image.getpixel((x,y))+8)//17 for y in range(height) for x in range(width)]
            if char!=' ' and not any(pixels):raise SystemExit(f'Empty glyph: {char}')
            records.append((ord(char),scale,width,height,width,len(bitmap)))
            for i in range(0,len(pixels),2):bitmap.append((pixels[i]<<4)|(pixels[i+1] if i+1<len(pixels) else 0))
    lines.append('static const uint8_t an_font_alpha[] = {')
    for i in range(0,len(bitmap),24):lines.append('    '+','.join(str(v) for v in bitmap[i:i+24])+',')
    lines+=['};','static const an_cjk_glyph_t an_cjk_glyphs[] = {']
    for code,scale,w,h,advance,offset in records:lines.append(f'    {{0x{code:04X},{scale},{w},{h},{advance},{offset}}},')
    lines+=['};','#define AN_CJK_GLYPH_COUNT (sizeof(an_cjk_glyphs)/sizeof(an_cjk_glyphs[0]))','']
    OUT.write_text('\n'.join(lines))
    print(f'Generated {len(records)} native-size glyphs, {len(bitmap)} bitmap bytes')
