#pragma once
#define AN_MEDAL_GOAL "通关  满血  连格三次"
#define AN_RIPOSTE "连段反击"
#define AN_TITLE_TEXT "夜巷忍者"
#define AN_SUBTITLE "读招格挡  左右反击"
#define AN_START "短按 B 开始"
#define AN_CONTROL "A 左斩  C 右斩  B 格挡"
#define AN_SELECT "A/C 选关  长 A 声音"
#define AN_PAUSED_TEXT "已暂停"
#define AN_FAILED_TEXT "夜巷失守"
#define AN_CLEAR_TEXT "黎明将至"
#define AN_WON "街巷清空"
#define AN_RESUME "短按 B 继续"
#define AN_EXIT "长按 A 返回标题"
#define AN_HOME "长按 B 返回标题"
#define AN_RETRY "短按 B 重试"
#define AN_NEXT "短按 B 下一关"
#define AN_SCORE "分数"
#define AN_BEST "最佳"
#define AN_PROGRESS "击退"
#define AN_SOUND "声音开"
#define AN_MUTED "声音关"
#define AN_READY "A/C 斩击  长 C 暂停"
#define AN_GUARD "格挡中  松 B 再反击"
#define AN_PERFECT "完美格挡"
#define AN_BLOCK "挡住了  快反击"
#define AN_ARMOR "护甲未破  先格挡"
#define AN_MISS "距离太远或方向不对"
#define AN_HIT "斩击命中"
#define AN_HURT "受击"
#define AN_BROKEN "体力不足  暂停格挡"
#define AN_WARNING "准备出招"
#define AN_COUNTER "反击窗口"
#define AN_STAMINA "体力"
static const char *const an_stage_names[]={"初入夜巷","两侧来袭","铁甲试炼","错拍街区","影卫决战"};
static const char *const an_feedback[]={"",AN_PERFECT,AN_BLOCK,AN_ARMOR,AN_MISS,AN_HIT,AN_HURT,AN_BROKEN};

#define AN_TUTORIAL "红条预警 按住 B 格挡"
#define AN_LEFT_HINT "松 B 按 A 左斩"
#define AN_RIGHT_HINT "松 B 按 C 右斩"
