#pragma once
#define BW_MEDAL_GOAL "通关  满生命  留有减速"
#define BW_SUPPLY "击碎六砖  补充减速"
#define BW_TITLE_TEXT "弹砖工坊"
#define BW_SUBTITLE "挡住光球  击碎彩砖"
#define BW_START "短按 B 开始"
#define BW_CONTROL "按住 A/C 移动挡板"
#define BW_SELECT "A/C 选关  长 A 声音"
#define BW_PAUSED_TEXT "已暂停"
#define BW_FAILED_TEXT "光球用完了"
#define BW_CLEAR_TEXT "工坊点亮了"
#define BW_WON "砖墙清空"
#define BW_RESUME "短按 B 继续"
#define BW_EXIT "长按 A 返回标题"
#define BW_HOME "长按 B 返回标题"
#define BW_RETRY "短按 B 重试"
#define BW_NEXT "短按 B 下一关"
#define BW_SCORE "分数"
#define BW_BEST "最佳"
#define BW_PROGRESS "剩余"
#define BW_SOUND "声音开"
#define BW_MUTED "声音关"
#define BW_READY "短 B 发球  长 B 暂停"
#define BW_ACTION "短 B 减速  长 B 暂停"
#define BW_SLOW "减速场生效"
#define BW_EMPTY "减速已用完  长 B 暂停"
#define BW_ASSIST "弹道导向"
#define BW_USES "减速"
static const char *const bw_stage_names[]={"彩窗初光","双层玻璃","反弹支架","流动彩窗","光谱工坊"};

#define BW_TUTORIAL "A 左 C 右 接住光球"
